[package]
name = "bouncy-game"
version = "0.1.0"
authors = ["Kalebu Gwalugano <isaackeinstein@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
